version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10
    environment:
      DISPLAY: :99
      PIP_PROGRESS_BAR: 'off' # Disabling the progress bar

jobs:
  build-and-test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils
      - run:
          name: Install Python dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest pytest-qt PyQt5 pytest-xvfb
      - run:
          name: Set up environment
          command: |
            echo 'export PYTHONPATH="$PYTHONPATH:$(pwd)"' >> $BASH_ENV
            echo 'export QT_QPA_PLATFORM=offscreen' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            xvfb-run -a pytest tests/test_AI_NumberOfOutputs.py -v
            xvfb-run -a pytest tests/test_AI_PredictedCity.py -v
            xvfb-run -a pytest tests/test_AI_Preprocessing.py -v
            xvfb-run -a pytest tests/test_ButtonPanel.py -v
            xvfb-run -a pytest tests/test_IconsExist.py -v
            xvfb-run -a pytest tests/test_InformationDialog.py -v
            xvfb-run -a pytest tests/test_ModelExist.py -v
            xvfb-run -a pytest tests/test_SelectMethod.py -v
            xvfb-run -a pytest tests/test_sort_button.py -v

  build-and-push:
    docker:
      - image: docker:20.10.7
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_USER/vision_ai:${CIRCLE_SHA1} .
      - run:
          name: Log in to Docker Hub
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Push Docker image
          command: docker push $DOCKER_USER/vision_ai:${CIRCLE_SHA1}

workflows:
  version: 2
  build-test-and-push:
    jobs:
      - build-and-test
      - build-and-push:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main
