version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.10
    environment:
      DISPLAY: :99

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y xvfb
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install PyQt5 pytest pytest-qt
      - run:
          name: Run tests with Xvfb
          command: |
            . venv/bin/activate
            xvfb-run -a pytest tests/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
