version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.10

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install PyQt5 pytest pytest-qt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest tests/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
